####################################################################
# Install/Setup GeoIP
# https://docs.zeek.org/en/stable/frameworks/geoip.html
####################################################################
- name: Stat GeoIP database
  stat:
    path: '/usr/share/GeoIP/GeoLite2-City.mmdb'
  register: geoip_stat

- name: Download and extract GeoIP database
  unarchive:
    src: '{{ geoip_url }}'
    dest: '/usr/share/GeoIP/'
    remote_src: yes
  when: not geoip_stat.stat.exists

################################################################
# Compile Zeek
################################################################
- name: Check whether zeek is installed
  stat:
    path: /usr/local/zeek/bin/zeekctl
  register: zeek_stat

- name: Clone zeek repo
  git:
    repo: '{{ zeek_url }}'
    dest: '/tmp/zeek'
    recursive: yes
  when: not zeek_stat.stat.exists

- name: Debug msg
  debug:
    msg: 'WARNING - Compiling Zeek from source can take up to 30mins'
  when: not zeek_stat.stat.exists

- name: Configure zeek
  shell: ./configure --with-pcap={{ pf_ring_dir }}
  args:
    chdir: '/tmp/zeek'
  when: not zeek_stat.stat.exists

- name: Compile zeek
  make:
    chdir: '/tmp/zeek'
  when: not zeek_stat.stat.exists

- name: Install zeek
  make:
    chdir: '/tmp/zeek'
    target: install
  when: not zeek_stat.stat.exists

####################################################################
# Configure Zeek
####################################################################
- name: Set the interface
  lineinfile:  
    path: '/usr/local/zeek/etc/node.cfg'
    regexp: '^interface='
    line: 'interface={{ zeek_interface }}'

#Configure OUI logging
- name: Download OUI logging script
  get_url:
    url: https://raw.githubusercontent.com/iamckn/zeek-oui/master/oui-logging.zeek
    dest: /usr/local/zeek/share/zeek/policy/protocols/conn/oui-logging.zeek
    owner: root
    group: root

- name: Download OUI database                    
  get_url:
    url: https://raw.githubusercontent.com/iamckn/zeek-oui/master/oui.dat
    dest: /usr/local/zeek/share/zeek/policy/protocols/conn/oui.dat
    owner: root
    group: root

- name: Load additional zeek scripts  
  lineinfile:                                
    path: '/usr/local/zeek/share/zeek/site/local.zeek'
    line: '{{ item }}'
    state: present
    create: yes
  with_items:
    - '@load policy/protocols/conn/mac-logging'
    - '@load policy/protocols/conn/oui-logging'
    - '@load policy/tuning/json-logs.zeek'

####################################################################
# Zeek deploy
####################################################################
- name: Run zeek deploy
  shell: '/usr/local/zeek/bin/zeekctl {{ item }}'
  with_items:
    - 'install'
    - 'deploy'
    - 'status'

####################################################################
# Set zeek to start at boot
####################################################################
- name: Start zeek at boot
  cron:
    name: "zeek cron"
    minute: "0-59/5"
    job: "/usr/local/zeek/bin/zeekctl"
