################################################################
# Apt upgrade
################################################################
- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
    force_apt_get: True  

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
    force_apt_get: True 

####################################################################
#  Setup Timedatectl
####################################################################
- name: Set time to {{ timezone }}
  timezone: 
    name: '{{ timezone }}'

################################################################
# Install prereqs
################################################################
- name: Install prereqs
  apt:
    name:
      - 'git'
      - 'cmake'
      - 'make' 
      - 'gcc' 
      - 'g++' 
      - 'flex' 
      - 'bison' 
      - 'libcap-ng0'
      - 'libpcap-dev'
      - 'libcap-ng-dev' 
      - 'libssl-dev' 
      - 'python-dev'
      - 'python3-dev' 
      - 'swig' 
      - 'zlib1g'
      - 'zlib1g-dev'
      - 'libgeoip-dev'
      - 'build-essential' 
      - 'libelf-dev'
      - 'libpcre3'
      - 'libpcre3-dbg'
      - 'libpcre3-dev'
      - 'autoconf'
      - 'automake'
      - 'libtool'
      - 'libnet1-dev'
      - 'libyaml-0-2'
      - 'libyaml-dev'
      - 'libmagic-dev'
      - 'libnuma-dev'
      - 'pkg-config'
      - 'sendmail'
      - 'libmaxminddb-dev'
    state: present
    update_cache: true
